### ISSUE TITLE
Unrecognized message from Carabiner

### ISSUE THREAD

**Issue by marek-memsql** [brunchboy/beat-carabiner#1] opened 2017-04-04 15:34 UTC
Tried on RPI and it works (mostly)!
The beat-carabiner finds the players, attaches to the master, sends the beat info to the Carabiner and this one provides the Ableton Link connectivity via the RPI's wifi... All the connected devices are responding to the pitch changes pretty swiftly which is good...

BUT I am getting lots of errors like the one below and having a hard time to keep things in time - tested on my ipad and the ipad is not in sync with the players.

`2017-Apr-04 13:26:36 ERROR [beat-carabiner.carabiner:96] - Unrecognized message from Carabiner: bad-time 32986112821 4.0`

Marek

**Comment by brunchboy** [comment] 2017-04-04 16:35
Hmm, that means that for some reason the C++ library on the RPI is not able to parse `32986112821` as a `long`. The code is here: https://github.com/brunchboy/carabiner/blob/master/carabiner.cpp#L88-L92

**Comment by marek-memsql** [comment] 2017-04-04 18:38
Seems we are getting out of bounds. 
> long	4	long int, signed long int	–2,147,483,648 to 2,147,483,647

I had to change the datatype of "when" from "long" to "long long" so values 32986112821 fits there.
I am no longer getting the error but the ableton is getting synced off beat for some reason (ableton is too early)..

```
2017-Apr-04 18:21:05 INFO [beat-carabiner.core:215] - Virtual CDJ running as Player 5
2017-Apr-04 18:21:05 INFO [beat-carabiner.carabiner:155] - Locking Ableton Link tempo to 174.0
2017-Apr-04 18:21:13 INFO [beat-carabiner.core:229] - Trying to connect to Carabiner daemon on port 17000 with latency 20
2017-Apr-04 18:21:13 INFO [beat-carabiner.carabiner:81] - Connected to Carabiner.
2017-Apr-04 18:21:13 INFO [beat-carabiner.carabiner:74] - Realigning Ableton Link to beat 228969 by 0.9973060000047553
2017-Apr-04 18:21:34 INFO [beat-carabiner.carabiner:74] - Realigning Ableton Link to beat 248323 by 0.7901420000125654
2017-Apr-04 18:21:35 INFO [beat-carabiner.carabiner:74] - Realigning Ableton Link to beat 245536 by 0.8129649999900721
2017-Apr-04 18:21:35 INFO [beat-carabiner.carabiner:74] - Realigning Ableton Link to beat 259514 by 0.8465469999937341
2017-Apr-04 18:21:35 INFO [beat-carabiner.carabiner:74] - Realigning Ableton Link to beat 278806 by 0.5298199999961071
2017-Apr-04 18:21:36 INFO [beat-carabiner.carabiner:74] - Realigning Ableton Link to beat 278807 by 0.05090400000335649
2017-Apr-04 18:21:37 INFO [beat-carabiner.carabiner:74] - Realigning Ableton Link to beat 278812 by 0.9941649999818765
```

**Comment by maaraneasi** [comment] 2017-04-08 11:39
I am almost 100% sure that the problem is in the beat-carabiner - did few tests on my macbook to see if there is some problem caused by the RPI and its not as I am having the same issue when running on my laptop...
1) When using the classic beat-link-trigger & Carabiner, everything is fine and I am on time.
2) But if I replace the beat-link-trigger with beat-carabiner, it attaches to the Carabiner but I am off beat, same like when running on the RPI.

Is there everything ok with the latency broadcast to the link so the compensation works as expected?
I tried to check the code but must admit that the Clojure is unreadable for me.. :-D

**Comment by brunchboy** [comment] 2017-04-08 18:22
Hmm, thanks for the update, I will see if I can reproduce that here. Knowing it behaves the same way for you on your Mac makes it much easier. Also, looking at that log, it seems almost as if the realignment attempts are failing somehow.

One saving grace is that there isn’t much code involved, so finding the problem shouldn’t be too hard given that I can read the Clojure. ^_^

**Comment by brunchboy** [comment] 2017-04-08 22:17
I’m afraid I just can’t reproduce this. When I run either beat-link-trigger or beat-carabiner plugged in to the same router as the mixer and CDJs, with latency set to 15 or 20 milliseconds, it keeps Link synced nicely to whatever tracks I play. The are two or three small adjustments on the first few beats if I’ve made a big jump when starting a new track, but it stabilizes and then just reacts to the tempo as I change them, with only a rare adjustment needed. Essentially the same code is being used in both beat-link-trigger and beat-carabiner, so I am not surprised I am seeing the same results from each.

What is the speed of your ethernet network? What is the topology? Are you trying to use a wireless network? That would likely have too much jitter to be very satisfactory.

**Comment by maaraneasi** [comment] 2017-04-11 09:11
You are right and I am sorry... :) I gave it another try and it works fine on my mac so it was just a temporary glitch.
My network is very simple - I have a dedicated switch only for my dj rig so there is no dhcp or anything... The ping to the players from the rpi is less than 0.2ms and ping to the rpi is about 2ms when connected to the AP it creates so the network doesn't seems to be the issue here.
I did a few tests over the weekend and also recompiled the whole beat-carabiner directly on the rpi etc. etc. but its still the same. Starting the application also takes long (lets say 30s before it attaches to the players on the network) but the system is almost 99% idle. After doing some reading yesterday evening, I suspect it might be the clojure that doesn't play nicely on the rpi and causes the lag.. :-(

**Comment by brunchboy** [comment] 2017-04-12 03:53
No worries! I am glad it at least works on your Mac. I wonder what could be the issue with Clojure and the Pi? Perhaps not enough RAM? Clojure does have a lengthy startup time, but performs quite fast once it is up and running, I can run really large light shows using it.

But even if that is true, beat-carabiner is very small; it would be fairly easy to rewrite in another language. Let me know if you want help understanding the code someday… although, actually, that would not help you much, because the beat-link library—which you would still need to talk to or reimplement—is large and complex by comparison, and it is Java itself which has hefty memory requirements, not Clojure.

**Comment by maaraneasi** [comment] 2017-04-22 10:59
Good news everyone - got it working!
As the clojure code wasn't much different, I focused on the Carabiner itself and the Ableton Link library used as the submodule. 
1) I have added some gcc flags to optimize the code for the arm
2) Updated the Link API because the one used in the carabiner is outdated ( @brunchboy you might consider updating to the latest commit because they made quite nice changes). The latest version does play nicely on Linux thanks to the new clock abstraction
3) Backported the GCC 6.3 to my debian Jessie (the requirement by the Link was not fulfilled as the distribution package was 4.something) so I used the GCC from debian Stretch (and hit no bug...hmmm.....)
4) I had to hardcode the port and the polling rate to omit the gflags
^^
I don't know what is wrong with the gflags but it doesn't parse the port and the polling rate so the mongoose doesn't bind (or the tcp:// string is malformed for an unknown reason).
This is not a big deal as the gflags are being used only for the parameter parsing and this can be worked around quite easily without bothering with the gflags at all...

Anyway, I have got a very first version that syncs with the pioneer link properly and will continue working on it...

**Comment by brunchboy** [comment] 2017-04-22 19:01
That’s great news, and thanks for sharing the video. I will update the Link git submodule as you suggest, hopefully this weekend. I have seen activity on the project, so I am not surprised to hear there is new stuff. What is nicest that they have improved?

As far as gflags, that is frustrating! I only grabbed that package because it looked fast to integrate with a cmake based project, but it does seem bloated and overly complex for my needs; if you have a recommendation for an alternate command line argument parsing library that works well on the Pi, I would definitely appreciate the suggestion, and may look into switching.

**Comment by brunchboy** [comment] 2017-04-22 20:02
Ah! I bet [this commit](https://github.com/Ableton/link/commit/f37b87d1ecaa670ea0aba8bd0e631f321714cca5) in the Link project was the update you needed to get things working for you on the Pi! Neat stuff indeed. That relationship is exactly what Carabiner relies on, and it sounds like the Sonic Pi developers are implementing something very much like Carabiner.

**Comment by maaraneasi** [comment] 2017-04-24 07:42
Yeah this was the dealmaker :-) Spent all the weekend by messing with my rpi and wondering how smooth the sync is :-DD As the RPi3 is almost 99% idle when running the "stack", I will try to recompile the Carabiner for the new RPi Zero W and see how it runs there - if it runs on this smaller form factor device, even better... Need to lear more about the cmake and find a way how to crate one cmakefile so this can be compiled on every platform and merged back to your repo - atm, each version is platform dependent...

As for the command line arguments, I am thinking about removing the gflags at all from my fork and try to use 
https://github.com/jarro2783/cxxopts instead - this is header only library so should be pretty lightweight and more than enough for parsing just 2 arguments.

Also thinking about expanding the functionality of the beat-carabiner and sending the midi clock to the connected usb -> midi converter at the same time (the relevant parts should be already in the beat-link-trigger so will try to somehow digest the clojure code :-/ ).
Not sure if I will be able to implement it but for me it makes sense to have it there as well so you can plug in any midi device and get synced - if nothing, it will be fun to try....

Last but not least messing with this made me to learn some new stuff around the cmake, clojure etc. so thumbs up :-)

**Comment by brunchboy** [comment] 2017-07-02 22:39
Is there anything left to do on this issue? Will you be able to submit a pull request with any changes you needed to make, as long as they are compatible with the other environments it builds for as well?

**Comment by maaraneasi** [comment] 2017-07-20 18:22
Hi, sorry for delayed response.
I haven't much time recently to work on this project but I will find some time to finish it.
Basically what's pending is to change the cmake so it automatically stets the flags based on the architecture...

**Comment by brunchboy** [comment] 2017-07-20 22:00
No worries! There is no deadline; I have been feeling like I should try to figure out how to do it myself, but have been too busy with other things as well. I am happy to hear that you are willing to tackle it someday, and will leave it to you.

**Comment by brunchboy** [comment] 2018-09-22 06:20
Any hope of getting this closed out?

**Comment by brunchboy** [comment] 2019-11-01 02:55
I think this is no longer relevant because this project is turning into a library that will be used by both Beat Link Trigger and Open Beat Control. You should be able to use Open Beat Control with Pure Data to do any kind of MIDI integration you want.

**Closed as completed by brunchboy** 2019-11-01 02:55 UTC
